name: Deploy Azure Network (VNet)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.9.5
  TF_WORKING_DIR: terraform/workloads
  ENV_DIR: terraform/workloads/envs/${{ github.event.inputs.environment }}

jobs:
  terraform-network:
    name: Deploy VNet Infrastructure
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
          -backend-config="${{ env.ENV_DIR }}/backend.tf"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
          -var-file="${{ env.ENV_DIR }}/vnet.tfvars"

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform apply -auto-approve \
          -var-file="${{ env.ENV_DIR }}/vnet.tfvars"
