name: Destroy Azure Database (MySQL)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.9.5
  TF_WORKING_DIR: terraform/database
  ENV_NAME: ${{ github.event.inputs.environment }}

  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform-database-destroy:
    name: Destroy Database Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Copy Backend Configuration
        run: |
          cp terraform/database/envs/${{ env.ENV_NAME }}/backend.tf terraform/database/backend.tf

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -destroy -var-file="envs/${{ env.ENV_NAME }}/database.tfvars"

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var-file="envs/${{ env.ENV_NAME }}/database.tfvars"
